### ISSUE TITLE
Issue on Python Tutorial 8,9,10 (CtcsoundAPIExamples.ipynb)

### ISSUE THREAD

**Issue by dirkbosman** [csound/csoundAPI_examples#28]
I get the following errors while running the CtcsoundAPIExamples.ipynb file: 

**My Setup:** 
* Python 3.7
* Jupyter 1.0.0
* Numpy 1.16.1
* ctsound 0.0.3

**ERROR LOG:** 

ValueError                                Traceback (most recent call last)
~/Code/csound_python/venv/lib/python3.7/site-packages/numpy/core/_internal.py in _dtype_from_pep3118(spec)
    597     stream = _Stream(spec)
--> 598     dtype, align = __dtype_from_pep3118(stream, is_subdtype=False)
    599     return dtype

~/Code/csound_python/venv/lib/python3.7/site-packages/numpy/core/_internal.py in __dtype_from_pep3118(stream, is_subdtype)
    674         else:
--> 675             raise ValueError("Unknown PEP 3118 data type specifier %r" % stream.s)
    676 

ValueError: Unknown PEP 3118 data type specifier 'P'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-8-d8a0a26b25ae> in <module>
     68 
     69 # Create a set of ChannelUpdaters
---> 70 channels = [ChannelUpdater("amp", RandomLine(.4, .2)),
     71             ChannelUpdater("freq", RandomLine(400, 80)),
     72             ChannelUpdater("resonance", RandomLine(0.4, .3))]

<ipython-input-8-d8a0a26b25ae> in __init__(self, channelName, updater)
     30     def __init__(self, channelName, updater):
     31         self.updater = updater
---> 32         self.channel = createChannel(channelName)
     33 
     34     def update(self):

<ipython-input-8-d8a0a26b25ae> in createChannel(channelName)
     24 def createChannel(channelName):
     25     chn, _ = c.channelPtr(channelName,
---> 26     ctcsound.CSOUND_CONTROL_CHANNEL | ctcsound.CSOUND_INPUT_CHANNEL)
     27     return chn
     28 

~/Code/csound_python/venv/lib/python3.7/site-packages/ctcsound.py in channelPtr(self, name, type_)
   1592                 arrayType = np.ctypeslib.ndpointer(MYFLT, 1, (length,), 'C_CONTIGUOUS')
   1593                 p = cast(ptr, arrayType)
-> 1594                 return np.ctypeslib.as_array(p), err
   1595         elif ret == CSOUND_MEMORY:
   1596             err = 'Not enough memory for allocating channel'

~/Code/csound_python/venv/lib/python3.7/site-packages/numpy/ctypeslib.py in as_array(obj, shape)
    517             obj = ctypes.cast(obj, p_arr_type).contents
    518 
--> 519         return array(obj, copy=False)
    520 
    521 

ValueError: '<P' is not a valid PEP 3118 buffer format string

**Comment by fggp** [comment]
This is a known bug in recent versions of numpy. You should try to revert
to numpy 1.14

François

Le sam. 16 févr. 2019 à 13:03, dirkbosman <notifications@github.com> a
écrit :

**Comment by fggp** [comment]
To be more precise, it's a bug between numpy and ctypes (see
https://github.com/numpy/numpy/issues/12421). It appeared with numpy
1.15.2. Actually you can revert to numpy 1.14.6:

pip uninstall numpy
pip install numpy==1.14.6

I'll build a simple use case to submit the problem to numpy devs

François

**Comment by eric-wieser** [comment]
Replacing these lines:

https://github.com/csound/csound/blob/58879034e78fc495beb3f5e71554914ce0cdf98d/interfaces/ctcsound.py#L1172-L1174

With:

    arrayType = np.ctypeslib.ndpointer(MYFLT, 1, (size,), 'C_CONTIGUOUS')
    p = cast(buf, arrayType)
    return p.contents

Makes the problem go away

**Comment by fggp** [comment]
Yes. However this applies only to numpy >= 1.16.0 because the contents
method of ndpointer did not exist before version 1.16.0 and this breaks
backward compatibility with older versions of numpy.
I commited a correction to ctcsound on github that keeps the old version
when ctcsound detects numpy < 1.15, uses your solution when ctcsound
detects numpy >= 1.16 and stops with a warning message when ctcsound
detects numpy >= 1.15  and < 1.16.
Thanks
François

Le dim. 17 févr. 2019 à 20:00, Eric Wieser <notifications@github.com> a
écrit :
